### PR TITLE
Disable check disabled attribute, 禁用检查禁用属性

### PR DESCRIPTION
**Pull request by lwlsw**
Disable check disabled attribute, Because some binary files are sometimes started even if they are disabled.
禁用检查禁用属性，因为有的二进制文件即使是禁用状态，有时候也会启动。

### CODE REVIEW

**Comment by opa334** [comment]
I don't even remember why I put this check in lol, can you name any "Disabled" daemons that still get loaded?

**Comment by lwlsw** [comment]
This is the binary file
/usr/libexec/nanomediaremotelinkagent

This is the Daemon plist file
/System/Library/NanoLaunchDaemons/com.apple.nanomediaremotelinkagent.plist

I was the one who asked you to add the /System/ Library/NanoLaunchDaemons daemon on Twitter. At that time, you might be too busy, and I can't wait for you to update, so I learned to modify it myself.  Then I discovered that the daemon would be running even if it was disabled.

**Comment by opa334** [comment]
I meant to add those nano* daemons in earlier, I just forgot it. I will see what I can do about this.

**Comment by lwlsw** [comment]
It's okay, but I don't think it is necessary to check the disabled attributes

**Pull request closed without merging**
