### PR TITLE
Moved initialisation of Quick Actions icons

### PR DESCRIPTION
**Pull request by tomaszpoliszuk**
to applicationShortcutItems to simplify code.

### CODE REVIEW

**Comment by opa334** [comment]
you sure this supports dark mode on iOS 13 and up?

**Comment by tomaszpoliszuk** [comment]
Yes - tested this on iOS 13 & 14.

Have a nice day!

**Comment by opa334** [comment]
This seems to work just fine, thanks! I tried this before but it broke in dark mode, I think it's the isTemplate:1 in the call that fixes that.

**Comment by tomaszpoliszuk** [comment]
Exactly - it didn't worked correctly until I've set isTemplate to 1 :)

**Pull request merged**
